[package]
authors = ["Tait Hoyem <tait@tait.tech>"]
name = "odilia-common"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
smartstring = "0.2.9"
thiserror = "1.0.30"
